### ISSUE TITLE
Switch root namespace to bitExpert

### ISSUE THREAD

**Issue by shochdoerfer** [bitExpert/testiat-api-client-php#4]
Not sure if testi.at will like if we grab "their" namespace. Maybe it's better to use a namespace like `\bitExpert\Testiat` instead. Otherwise feel free to move the package to a testiat organization (after talking to the testiat people of course).

**Comment by DanielRuf** [comment]
Currently https://github.com/testiat/testiat-api-client-php/ is a fork.

I'll change the namespace to the suggested one as we maintain it.
