### ISSUE TITLE
Add support for PSR-7 / PSR-18

### ISSUE THREAD

**Issue by shochdoerfer** [bitExpert/testiat-api-client-php#6]
Instead of using low-level curl calls, we should migrate the package to make use of the PSR-7 and PSR-18 standards so that anyone could plug in their own specific HTTP client library and we don't have a hard curl dependency.

**Comment by shochdoerfer** [comment]
This should also help with #1 regarding mock objects needed for the tests.

**Comment by DanielRuf** [comment]
Hi @shochdoerfer,

not sure if the linked PR is the right / best approach but the maintainer seems to be one of the people behind the PSR-18 / HTTPlug initiative and seemed to be very promising.

**Comment by DanielRuf** [comment]
Not sure if I got this right.

**Comment by DanielRuf** [comment]
What do you suggest for the current variant? Move it to some other repository for those users who can not / do not want to use Composer or setup a client to consume the results?

Like some sort of "legacy" single-file poor mans version?
